//
//  ISMacroDefinitions.h
//  iSignal
//
//  Created by Patrick Deng on 12-3-8.
//  Copyright (c) 2012年 CodeBeaver. All rights reserved.
//

#ifndef iSignal_ISMacroDefinitions_h
#define iSignal_ISMacroDefinitions_h

// App Configs
#define APPCONFIG_ALARM_RING @"cfg_alarm_ring"
#define APPCONFIG_ALARM_VIBRATE @"cfg_alarm_vibrate"
#define APPCONFIG_LOCATION @"cfg_location"
#define APPCONFIG_NOTIFICATION @"cfg_notification"


// Modules
#define MODULE_ID_DUMMYTEPLEPHONY @"Dummy Telephony Module"
#define MODULE_ID_COREDATA @"Core Data Module"
#define MODULE_ID_AUDIO @"Audio Module"
#define MODULE_ID_LOCALNOTIFICATION @"UI LocalNotification Module"
#define MODULE_ID_APPCONFIGS @"App Configugration Module"


// Notifications
#define NOTIFICATION_TYPE @"NotificationType"
#define NOTIFICATION_NOSIGNAL @"NoSignal"
#define NOTIFICATION_ID_SIGNALSTRENGTH_CHANGED @"NO_SIGNAL"
#define NOTIFICATION_KV_SIGNALSTRENGTH_CHANGED @"SIGNALSTRENGTH_VALUE"


// Resources
#define AUDIO_TYPE_CAF @"caf"
#define AUDIO_NO_SIGNAL @"signalLost"


// Database
#define DB_ISIGNAL_PATH_COMPONENT @"iSignal.sqlite"
#define DB_ISIGNAL_MANAGEMENT_MODEL_NAME @"iSignal"
#define DB_ISIGNAL_MANAGEMENT_MODEL_EXTENSION @"momd"
#define DB_TABLE_SIGNALRECORD_CACHE @"SignalRecord_CoreData_Cache"
#define DB_TABLE_SIGNALRECORD @"SignalRecord"
#define DB_TABLE_SIGNALRECORD_FIELD_DURATION @"duration"
#define DB_TABLE_SIGNALRECORD_FIELD_TIME @"time"
#define DB_TABLE_SIGNALRECORD_FIELD_ISSYNC @"isSync"
#define DB_TABLE_SIGNALRECORD_FIELD_LATITUDE @"latitude"
#define DB_TABLE_SIGNALRECORD_FIELD_LONGITUDE @"longitude"
#define DB_TABLE_SIGNALRECORD_FIELD_TAG @"tag"
#define DB_TABLE_SIGNALRECORD_FIELD_TYPE @"type"
#define DB_TABLE_SIGNALRECORD_VALUE_NOSIGNAL QUALITY_SIGNAL_NO
#define DB_TABLE_SIGNALRECORD_FETCH_BATCH_SIZE 20
#define DB_TABLE_SIGNALRECORD_FETCH_ASCENDING NO


// Telephony
#define CARRIER_CMCC 0
#define CARRIER_CUNI 1

#define CELLULAR_SIGNALSTRENGTH_HIGHEST -50
#define CELLULAR_SIGNALSTRENGTH_LOWEST -110
#define CELLULAR_SIGNALSTRENGTH_LOSS 20

#define DUMMY_REFRESH_PERIOD_SMALL 5
#define DUMMY_REFRESH_PERIOD_LONG 10


// UI - TabViews
#define TABVIEW_COUNT 5
#define TABVIEW_INDEX_SWITCHVIEW 0
#define TABVIEW_INDEX_HOMEVIEW 1
#define TABVIEW_INDEX_RECORDSVIEW 2
#define TABVIEW_INDEX_MAPVIEW 3
#define TABVIEW_INDEX_CONFIGVIEW 4
#define TABVIEW_INDEX_HELPVIEW 5

// UI - NIB Files
#define NIB_HOMEVIEW_CONTROLLER @"ISHomeViewController"
#define NIB_RECORDSVIEW_CONTROLLER @"ISRecordsViewController"
#define NIB_MAPVIEW_CONTROLLER @"ISMapViewController"
#define NIB_CONFIGVIEW_CONTROLLER @"ISConfigViewController"
#define NIB_HELPVIEW_CONTROLLER @"ISHelpViewController"


// UI - Tables
// ISConfigView Config Table
#define TABLECELL_TYPE_APPCONFIG @"CellType_AppConfig"
#define TABLE_CONFIG_SECTION_COUNT 1
#define TABLE_CONFIG_SECTION_INDEX_CONFIG 0
#define TABLE_CONFIG_SECTION_NAME_CONFIG NSLocalizedString(@"STR_CONFIG", nil)
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_COUNT 4
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_RING_INDEX 0
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_RING_NAME NSLocalizedString(@"STR_RING", nil)
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_VIBRATE_INDEX 1
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_VIBRATE_NAME NSLocalizedString(@"STR_VIBRATE", nil)
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_LOCATION_INDEX 2
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_LOCATION_NAME NSLocalizedString(@"STR_LOCATION", nil)
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_NOTIFICATION_INDEX 3
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_NOTIFICATION_NAME NSLocalizedString(@"STR_NOTIFICATION", nil)
// ISRecordsView Records Table
#define TABLECELL_TYPE_SIGNALRECORD @"CellType_SignalRecord"
// ISRecordDetailView RecordDetail Table
#define TABLECELL_TYPE_SIGNALRECORDDETAIL @"CellType_SignalRecordDetail"
#define TABLE_SIGNALRECORDDETAIL_SECTION_COUNT 1
#define TABLE_SIGNALRECORDDETAIL_INDEX_DETAIL 0
#define TABLE_SIGNALRECORDDETAIL_NAME_DETAIL NSLocalizedString(@"STR_DETAIL", nil)
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_COUNT 3
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_CARRIER_INDEX 0
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_NAME_CARRIER NSLocalizedString(@"STR_CARRIER", nil)
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_TYPE_INDEX 1
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_TYPE_NAME NSLocalizedString(@"STR_TYPE", nil)
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_TIME_INDEX 2
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_TIME_NAME NSLocalizedString(@"STR_TIME", nil)


// UI - Maps
#define ISMAPVIEW_SPAN_LONGITUDE 2000
#define ISMAPVIEW_SPAN_LATITUDE 2000


#endif
