//
//  ISMacroDefinitions.h
//  iSignal
//
//  Created by Patrick Deng on 12-3-8.
//  Copyright (c) 2012年 CodeBeaver. All rights reserved.
//

#ifndef iSignal_ISMacroDefinitions_h
#define iSignal_ISMacroDefinitions_h

// App Configs
#define CONFIG_ALARM_RING @"cfg_alarm_ring"
#define CONFIG_ALARM_VIBRATE @"cfg_alarm_vibrate"
#define CONFIG_LOCATION @"cfg_location"
#define CONFIG_NOTIFICATION @"cfg_notification"


// Modules
#define MODULE_ID_DUMMYTEPLEPHONY @"Dummy Telephony Module"
#define MODULE_ID_COREDATA @"Core Data Module"
#define MODULE_IDENTITY_AUDIO_MODULE @"Audio Module"
#define MODULE_IDENTITY_UILOCALNOTIFICATION_MODULE @"UI LocalNotification Module"
#define MODULE_IDENTITY_APP_CONFIGS @"App Configugration Module"


// Notifications
#define NOTIFICATION_TYPE @"NotificationType"
#define NOTIFICATION_NOSIGNAL @"NoSignal"
#define NOTIFICATION_ID_SIGNALSTRENGTH_CHANGED @"NO_SIGNAL"
#define NOTIFICATION_KV_SIGNALSTRENGTH_CHANGED @"SIGNALSTRENGTH_VALUE"


// Resources
#define AUDIO_TYPE_CAF @"caf"
#define AUDIO_NO_SIGNAL @"signalLost"


// Database
#define DB_ISIGNAL_PATH_COMPONENT @"iSignal.sqlite"
#define DB_ISIGNAL_MANAGEMENT_MODEL_NAME @"iSignal"
#define DB_ISIGNAL_MANAGEMENT_MODEL_EXTENSION @"momd"
#define DB_TABLE_SIGNALRECORD_CACHE @"SignalRecord_CoreData_Cache"
#define DB_TABLE_SIGNALRECORD @"SignalRecord"
#define DB_TABLE_SIGNALRECORD_FIELD_DURATION @"duration"
#define DB_TABLE_SIGNALRECORD_FIELD_TIME @"time"
#define DB_TABLE_SIGNALRECORD_FIELD_ISSYNC @"isSync"
#define DB_TABLE_SIGNALRECORD_FIELD_LATITUDE @"latitude"
#define DB_TABLE_SIGNALRECORD_FIELD_LONGITUDE @"longitude"
#define DB_TABLE_SIGNALRECORD_FIELD_TAG @"tag"
#define DB_TABLE_SIGNALRECORD_FIELD_TYPE @"type"
#define DB_TABLE_SIGNALRECORD_VALUE_NOSIGNAL QUALITY_SIGNAL_NO
#define DB_TABLE_SIGNALRECORD_VALUE_NULL @"N/A"
#define DB_FETCH_BTACH_SIZE 20
#define DB_ASCENDING NO


// Telephony
#define CARRIER_CMCC 0
#define CARRIER_CUNI 1

#define CELLULAR_SIGNAL_STRENGTH_HIGHEST -50
#define CELLULAR_SIGNAL_STRENGTH_LOWEST -110
#define CELLULAR_SIGNAL_STRENGTH_LOSS 20

#define REFRESH_PERIOD_SMALL 5
#define REFRESH_PERIOD_LONG 10


// UI - TabViews
#define TABVIEW_COUNT 5
#define TABVIEW_INDEX_ISSWITCHVIEW 0
#define TABVIEW_INDEX_ISHOMEVIEW 1
#define TABVIEW_INDEX_ISRECORDSVIEW 2
#define TABVIEW_INDEX_ISMAPVIEW 3
#define TABVIEW_INDEX_ISCONFIGVIEW 4
#define TABVIEW_INDEX_ISHELPVIEW 5

#define NIB_HOMEVIEW_CONTROLLER @"ISHomeViewController"
#define NIB_RECORDSVIEW_CONTROLLER @"ISRecordsViewController"
#define NIB_MAPVIEW_CONTROLLER @"ISMapViewController"
#define NIB_CONFIGVIEW_CONTROLLER @"ISConfigViewController"
#define NIB_HELPVIEW_CONTROLLER @"ISHelpViewController"


// UI - Tables
// ISConfigView Config Table
#define CELL_IDENTIFIER_APPCONFIG @"CellIdentifier_AppConfig"
#define CONFIG_TABLE_SECTION_COUNT 1
#define CONFIG_TABLE_SECTION_INDEX_CONFIG 0
#define CONFIG_TABLE_SECTION_NAME_CONFIG NSLocalizedString(@"STR_CONFIG", nil)
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_COUNT 4
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_RING_INDEX 0
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_RING_NAME NSLocalizedString(@"STR_RING", nil)
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_VIBRATE_INDEX 1
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_VIBRATE_NAME NSLocalizedString(@"STR_VIBRATE", nil)
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_LOCATION_INDEX 2
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_LOCATION_NAME NSLocalizedString(@"STR_LOCATION", nil)
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_NOTIFICATION_INDEX 3
#define CONFIG_TABLE_SECTION_CONFIG_ITEM_NOTIFICATION_NAME NSLocalizedString(@"STR_NOTIFICATION", nil)
// ISRecordsView Records Table
#define KEY_CELL_IDENTIFIER @"Cell"
#define KEY_CELL_SIGNALRECORD_IDENTIFIER @"SignalRecordCell"
// ISRecordDetailView RecordDetail Table
#define CELL_IDENTIFIER_SIGNALRECORD_DETAIL @"CellIdentifier_SignalRecordDetail"
#define DETAILTABLE_SECTION_COUNT 1
#define DETAILTABLE_SECTION_INDEX_DETAIL 0
#define DETAILTABLE_SECTION_NAME_DETAIL NSLocalizedString(@"STR_DETAIL", nil)
#define DETAILTABLE_SECTION_DETAIL_ITEM_COUNT 3
#define DETAILTABLE_SECTION_DETAIL_ITEM_CARRIER_INDEX 0
#define DETAILTABLE_SECTION_DETAIL_ITEM_CARRIER_NAME NSLocalizedString(@"STR_CARRIER", nil)
#define DETAILTABLE_SECTION_DETAIL_ITEM_TYPE_INDEX 1
#define DETAILTABLE_SECTION_DETAIL_ITEM_TYPE_NAME NSLocalizedString(@"STR_TYPE", nil)
#define DETAILTABLE_SECTION_DETAIL_ITEM_TIME_INDEX 2
#define DETAILTABLE_SECTION_DETAIL_ITEM_TIME_NAME NSLocalizedString(@"STR_TIME", nil)


// UI - Maps
#define ISMAPVIEW_SPAN_LONGITUDE 2000
#define ISMAPVIEW_SPAN_LATITUDE 2000


#endif
