//
//  ISMacroDefinitions.h
//  iSignal
//
//  Created by Patrick Deng on 12-3-8.
//  Copyright (c) 2012年 CodeBeaver. All rights reserved.
//

#ifndef iSignal_ISMacroDefinitions_h
#define iSignal_ISMacroDefinitions_h

// Author Information
#define AUTHOR_WEBSITE @""
#define AUTHOR_EMAIL @"motodexter@gmail.com"
#define AUTHOR_WEIBO @"@Patrick_Deng"
#define AUTHOR_TWITTER @"@motodexter"

// App Configs
#define APPCONFIG_ALARM_RING @"cfg_alarm_ring"
#define APPCONFIG_ALARM_VIBRATE @"cfg_alarm_vibrate"
#define APPCONFIG_LOCATION @"cfg_location"
#define APPCONFIG_NOTIFICATION @"cfg_notification"
#define APPCONFIG_DATA_CLEAR @"cfg_cleardata"


// Modules
#define MODULE_ID_DUMMYTEPLEPHONY @"Dummy Telephony Module"
#define MODULE_ID_COREDATA @"Core Data Module"
#define MODULE_ID_AUDIO @"Audio Module"
#define MODULE_ID_LOCALNOTIFICATION @"UI LocalNotification Module"
#define MODULE_ID_APPCONFIGS @"App Configugration Module"


// Notifications
#define NOTIFICATION_TYPE @"NotificationType"
#define NOTIFICATION_NOSIGNAL @"NoSignal"
#define NOTIFICATION_ID_SIGNALSTRENGTH_CHANGED @"NO_SIGNAL"
#define NOTIFICATION_KV_SIGNALSTRENGTH_CHANGED @"SIGNALSTRENGTH_VALUE"
#define NOTIFICATION_APPISTERMINATED @"AppIsTerminated"
#define NOTIFICATION_APPENTERSBACKGROUND @"AppEntersBackground"

// Resources
#define AUDIO_TYPE_CAF @"caf"
#define AUDIO_NO_SIGNAL @"signalLost"


// Database
#define DB_ISIGNAL_PATH_COMPONENT @"iSignal.sqlite"
#define DB_ISIGNAL_MANAGEMENT_MODEL_NAME @"iSignal"
#define DB_ISIGNAL_MANAGEMENT_MODEL_EXTENSION @"momd"
#define DB_TABLE_SIGNALRECORD_CACHE @"SignalRecord_CoreData_Cache"
#define DB_TABLE_SIGNALRECORD @"SignalRecord"
#define DB_TABLE_SIGNALRECORD_FIELD_DURATION @"duration"
#define DB_TABLE_SIGNALRECORD_FIELD_TIME @"time"
#define DB_TABLE_SIGNALRECORD_FIELD_ISSYNC @"isSync"
#define DB_TABLE_SIGNALRECORD_FIELD_LATITUDE @"latitude"
#define DB_TABLE_SIGNALRECORD_FIELD_LONGITUDE @"longitude"
#define DB_TABLE_SIGNALRECORD_FIELD_TAG @"tag"
#define DB_TABLE_SIGNALRECORD_FIELD_TYPE @"type"
#define DB_TABLE_SIGNALRECORD_FIELD_SPEED @"speed"
#define DB_TABLE_SIGNALRECORD_VALUE_NOSIGNAL QUALITY_SIGNAL_NO
#define DB_TABLE_SIGNALRECORD_FETCH_BATCH_SIZE 20
#define DB_TABLE_SIGNALRECORD_FETCH_ASCENDING NO


// Telephony
#define CARRIER_CMCC 0
#define CARRIER_CUNI 1

#define CELLULAR_SIGNALSTRENGTH_HIGHEST -50
#define CELLULAR_SIGNALSTRENGTH_LOWEST -110
#define CELLULAR_SIGNALSTRENGTH_LOSS 20

#define DUMMY_REFRESH_PERIOD_SMALL 5
#define DUMMY_REFRESH_PERIOD_LONG 10


// UI - TabViews
#define TABVIEW_INDEX_HOMEVIEW 1
#define TABVIEW_INDEX_RECORDSVIEW 2
#define TABVIEW_INDEX_MAPVIEW 3
#define TABVIEW_INDEX_MONITORVIEW 4
#define TABVIEW_INDEX_CONFIGVIEW 5
#define TABVIEW_INDEX_HELPVIEW 6

// UI - NIB Files
#define NIB_HOMEVIEW_CONTROLLER @"ISHomeViewController"
#define NIB_RECORDSVIEW_CONTROLLER @"ISRecordsViewController"
#define NIB_MAPVIEW_CONTROLLER @"ISMapViewController"
#define NIB_MONITORVIEW_CONTROLLER @"ISMonitorViewController"
#define NIB_CONFIGVIEW_CONTROLLER @"ISConfigViewController"
#define NIB_HELPVIEW_CONTROLLER @"ISHelpViewController"
#define NIB_TABLEVIEW_SWITCHERCELL @"ISTableViewSwitcherCell"

// UI - Tables
#define TABLECELL_TYPE_GENERIC @"CellType_Generic"
// ISConfigView Config Table
#define TABLECELL_TYPE_APPCONFIG @"CellType_AppConfig"
#define TABLE_CONFIG_SECTION_COUNT 2
#define TABLE_CONFIG_SECTION_INDEX_CONFIG 0
#define TABLE_CONFIG_SECTION_NAME_CONFIG NSLocalizedString(@"STR_CONFIG", nil)
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_COUNT 4
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_RING_INDEX 0
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_RING_NAME NSLocalizedString(@"STR_RING", nil)
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_VIBRATE_INDEX 1
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_VIBRATE_NAME NSLocalizedString(@"STR_VIBRATE", nil)
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_LOCATION_INDEX 2
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_LOCATION_NAME NSLocalizedString(@"STR_LOCATION", nil)
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_NOTIFICATION_INDEX 3
#define TABLE_CONFIG_SECTION_CONFIG_ITEM_NOTIFICATION_NAME NSLocalizedString(@"STR_NOTIFICATION", nil)
#define TABLE_CONFIG_SECTION_DATA_INDEX 1
#define TABLE_CONFIG_SECTION_DATA_NAME NSLocalizedString(@"STR_DATA", nil)
#define TABLE_CONFIG_SECTION_DATA_ITEM_DATASOURCE_INDEX 0
#define TABLE_CONFIG_SECTION_DATA_ITEM_DATASOURCE_NAME NSLocalizedString(@"STR_DATA_SOURCE", nil)
#define TABLE_CONFIG_SECTION_DATA_ITEM_CLEARDATA_INDEX 1
#define TABLE_CONFIG_SECTION_DATA_ITEM_CLEARDATA_NAME NSLocalizedString(@"STR_DATA_CLEAR", nil)

// ISRecordsView Records Table
#define TABLECELL_TYPE_SIGNALRECORD @"CellType_SignalRecord"
// ISRecordDetailView RecordDetail Table
#define TABLECELL_TYPE_SIGNALRECORDDETAIL @"CellType_SignalRecordDetail"
#define TABLE_SIGNALRECORDDETAIL_SECTION_COUNT 1
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_INDEX 0
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_NAME NSLocalizedString(@"STR_DETAIL", nil)
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_COUNT 5
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_CARRIER_INDEX 0
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_NAME_CARRIER NSLocalizedString(@"STR_CARRIER", nil)
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_TYPE_INDEX 1
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_TYPE_NAME NSLocalizedString(@"STR_TYPE", nil)
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_TIME_INDEX 2
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_TIME_NAME NSLocalizedString(@"STR_TIME", nil)
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_SPEED_INDEX 3
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_SPEED_NAME NSLocalizedString(@"STR_SPEED", nil)
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_ADDRESS_INDEX 4
#define TABLE_SIGNALRECORDDETAIL_SECTION_DETAIL_ITEM_ADDRESS_NAME NSLocalizedString(@"STR_ADDRESS", nil)

// ISHelpView Help Table
#define TABLECELL_TYPE_HELPITEM @"CellType_HelpItem"
#define TABLE_HELPITEM_SECTION_COUNT 3
#define TABLE_HELPITEM_SECTION_COPYRIGHT_INDEX 0
#define TABLE_HELPITEM_SECTION_COPYRIGHT_NAME NSLocalizedString(@"STR_COPYRIGHT", nil)
#define TABLE_HELPITEM_SECTION_COPYRIGHT_ITEM_COUNT 3
#define TABLE_HELPITEM_SECTION_COPYRIGHT_ITEM_VERSION_INDEX 0
#define TABLE_HELPITEM_SECTION_COPYRIGHT_ITEM_VERSION_NAME NSLocalizedString(@"STR_VERSION", nil)
#define TABLE_HELPITEM_SECTION_COPYRIGHT_ITEM_USERID_INDEX 1
#define TABLE_HELPITEM_SECTION_COPYRIGHT_ITEM_USERID_NAME NSLocalizedString(@"STR_USER_ID", nil)
#define TABLE_HELPITEM_SECTION_COPYRIGHT_ITEM_REGISTERCODE_INDEX 2
#define TABLE_HELPITEM_SECTION_COPYRIGHT_ITEM_REGISTERCODE_NAME NSLocalizedString(@"STR_REGISTER_CODE", nil)
#define TABLE_HELPITEM_SECTION_ABOUT_INDEX 1
#define TABLE_HELPITEM_SECTION_ABOUT_NAME NSLocalizedString(@"STR_ABOUT", nil)
#define TABLE_HELPITEM_SECTION_ABOUT_ITEM_COUNT 2
#define TABLE_HELPITEM_SECTION_ABOUT_ITEM_ABOUT_INDEX 0
#define TABLE_HELPITEM_SECTION_ABOUT_ITEM_ABOUT_NAME NSLocalizedString(@"STR_ABOUT", nil)
#define TABLE_HELPITEM_SECTION_ABOUT_ITEM_VERSIONHISTORY_INDEX 1
#define TABLE_HELPITEM_SECTION_ABOUT_ITEM_VERSIONHISTORY_NAME NSLocalizedString(@"STR_VERSION_HISTORY", nil)
#define TABLE_HELPITEM_SECTION_MOREAPPS_INDEX 2
#define TABLE_HELPITEM_SECTION_MOREAPPS_ITEM_COUNT 1
#define TABLE_HELPITEM_SECTION_MOREAPPS_ITEM_MOREAPPS_INDEX 0
#define TABLE_HELPITEM_SECTION_MOREAPPS_ITEM_MOREAPPS_NAME NSLocalizedString(@"STR_MORE_APPS", nil)

// ISHelpView About Table
#define TABLECELL_TYPE_ABOUTITEM @"CellType_AboutItem"
#define TABLE_ABOUTITEM_SECTION_COUNT 2
#define TABLE_ABOUTITEM_SECTION_ABOUT_INDEX 0
#define TABLE_ABOUTITEM_SECTION_ABOUT_NAME NSLocalizedString(@"STR_ABOUT", nil)
#define TABLE_ABOUTITEM_SECTION_ABOUT_ITEM_COUNT 1
#define TABLE_ABOUTITEM_SECTION_ABOUT_ITEM_ABOUT_INDEX 0
#define TABLE_ABOUTITEM_SECTION_AUTHOR_INDEX 1
#define TABLE_ABOUTITEM_SECTION_AUTHOR_NAME NSLocalizedString(@"STR_AUTHOR", nil)
#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_COUNT 3
//#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_OFFICIALWEBSITE_INDEX 0
//#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_OFFICIALWEBSITE_NAME NSLocalizedString(@"STR_OFFICIAL_WEBSITE", nil)
#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_OFFICIALEMAIL_INDEX 0
#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_OFFICIALEMAIL_NAME NSLocalizedString(@"STR_OFFICIAL_EMAIL", nil)
#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_OFFICIALWEIBO_INDEX 1
#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_OFFICIALWEIBO_NAME NSLocalizedString(@"STR_OFFICIAL_WEIBO", nil)
#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_OFFICIALTWITTER_INDEX 2
#define TABLE_ABOUTITEM_SECTION_AUTHOR_ITEM_OFFICIALTWITTER_NAME NSLocalizedString(@"STR_OFFICIAL_TWITTER", nil)

// ISHelpView Version History Table
#define TABLECELL_TYPE_VERSIONITEM @"CellType_VersionItem"
#define TABLE_VERSIONITEM_SECTION_COUNT 1
#define TABLE_VERSIONITEM_SECTION_ITEM_COUNT 1 // Item count in one section is always 1
#define TABLE_VERSIONITEM_SECTION_0_1_0_INDEX 0
#define TABLE_VERSIONITEM_SECTION_0_1_0_NAME @"Version 0.1.0"
#define TABLE_VERSIONITEM_SECTION_0_1_0_ITEM_DESCRIPTION NSLocalizedString(@"STR_VERSION_DESCRIPTION_0_1_0", nil)

// UI - Maps
#define ISMAPVIEW_SPAN_LONGITUDE 2000
#define ISMAPVIEW_SPAN_LATITUDE 2000


#endif
